export const PUBLISHED_LEVEL_SORT_OPTIONS = ['POPULARITY', 'CLEAR_RATE']
export const PUBLISHED_LEVEL_PERIOD_OPTIONS = [
  'ALL_TIME',
  'TODAY',
  'LAST_7_DAYS',
  'LAST_30_DAYS',
  'LAST_365_DAYS',
]
